# Tomcat
server:
  port: 8088
# Spring
spring:
  application:
    # 应用名称
    name: stock-service
    #  profiles:
    # 环境配置
  #    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
        namespace:
#seata客户端配置
seata:
  enabled: true
  application-id: seata_tx
  tx-service-group: seata_tx_group
  service:
    vgroup-mapping:
      seata_tx_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace:
      group: DEFAULT_GROUP
  data-source-proxy-mode: AT


grpc:
  client:
    grpc-stock-service:
      address: static://localhost:9000
      negotiationType: plaintext
    grpc-order-service:
        address: static://localhost:9001
        negotiationType: plaintext
